Obligatorio.JuegosOlimpicos/LibreriaWeb/Models/Atleta/AtletaViewModel.cs
using LogicaNegocio.Entidades;

namespace LibreriaWeb.Models.Atleta
{
    public class AtletaViewModel
    {
        public int Id { get; set; }
        public string Nombre { get; set; }
        public string Apellido { get; set; }
        public string Sexo { get; set; }
        public int Pais { get; set; }
        public List<Disciplina> Disciplinas { get; set; }
        public List<Disciplina> TodasLasDisciplinas { get; set; }
        public List<int> NuevasDisciplinasId { get; set; }
    }
}

Obligatorio.JuegosOlimpicos/LibreriaWeb/Controllers/AtletaController.cs
using LibreriaWeb.Models.Atleta;
using LogicaAplicacion.ImplementacionCasosDeUso.Atleta;
using LogicaNegocio.Entidades;
using LogicaNegocio.ExcepcionesEntidades;
using LogicaNegocio.InterfacesRepositorios;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;

namespace LibreriaWeb.Controllers
{
    public class AtletaController : Controller
    {
        public AltaAtleta AltaAtleta { get; set; } = new AltaAtleta();
        private readonly IRepositorioAtleta RepoAtleta;
        private readonly IRepositorioDisciplina RepoDisciplina;

        public AtletaController(IRepositorioAtleta repositorioAtleta, IRepositorioDisciplina repositorioDisciplina)
        {
            RepoAtleta = repositorioAtleta;
            RepoDisciplina = repositorioDisciplina;
        }

        public IActionResult AsignarDisciplinas(int atletaId)
        {
            
            var atleta = RepoAtleta.FindById(atletaId);
            var disciplinas = RepoDisciplina.FindAll();
            AtletaViewModel viewModel = null;
            try
            {
                viewModel = new AtletaViewModel
            {
                Id = atleta.Id,
                Nombre = atleta.Nombre,
                Apellido = atleta.Apellido,
                Disciplinas = atleta._disciplinas
            };
            }
            catch (AtletaException ex)
            {
                ViewBag.Mensaje = "Se produjo un error";
            }
            if(viewModel == null)
            {
                return RedirectToAction("ErrorPage");
            }
            return View(viewModel);
        }

        [HttpPost]
        public IActionResult AsignarDisciplinas(AtletaViewModel model)
        {
            var atleta = RepoAtleta.FindById(model.Id);

            var NuevasDisciplinas = RepoDisciplina.FindById(model.Id);
            foreach (var disciplina in RepoDisciplina.FindAll())
            {
                if (!atleta._disciplinas.Contains(disciplina))
                {
                    atleta._disciplinas.Add(disciplina);
                }
            }

            RepoAtleta.Update(atleta, atleta.Id);
            return RedirectToAction("Index");
        }
        // GET: AtletaController
        public ActionResult Index()
        {
            return View();
        }

        // GET: AtletaController/Details/5
        public ActionResult Details(int id)
        {
            return View();
        }

        // GET: AtletaController/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: AtletaController/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(AtletaViewModel atletaVM)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    Atleta atleta = new Atleta(atletaVM.Nombre, atletaVM.Apellido, atletaVM.Sexo, atletaVM.Pais);
                    AltaAtleta.Ejecutar(atleta);
                }

                return RedirectToAction("Index");
            }
            catch (AtletaException ex)
            {
                ViewBag.Mensaje = ex.Message;
            }
            catch (Exception ex)
            {
                ViewBag.Mensaje = "Se produjo un error";
            }
            return View();
        }

        // GET: AtletaController/Edit/5
        public ActionResult Edit(int id)
        {
            return View();
        }

        // POST: AtletaController/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(int id, IRepositorioAtleta RepoAtleta)
        {
            try
            {
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        // GET: AtletaController/Delete/5
        public ActionResult Delete(int id)
        {
            return View();
        }

        // POST: AtletaController/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(int id, IRepositorioAtleta RepoAtleta)
        {
            try
            {
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }
    }
}

Obligatorio.JuegosOlimpicos/LibreriaWeb/Views/Atleta/AsignarDisciplina.cshtml
@model LibreriaWeb.Models.Atleta.AtletaViewModel


@{
    ViewData["Title"] = "AsignarDisciplina";
}

    <h2>Asignar disciplinas a @Model.Nombre @Model.Apellido</h2>

    <form asp-controller="Atleta" asp-action="AsignarDisciplinas" method="post">

        <div>
            <label>Nuevas disciplinas</label>
            <select name="Disciplinas" multiple="multiple" class="form-control">
                @foreach (var disciplina in Model.TodasLasDisciplinas)
                {
                    <option value="@disciplina.Id">@disciplina.NombreDescriptivo</option>
                }
            </select>
        </div>

        <button class="btn btn-primary" type="submit">Guardar</button>
    </form>

Obligatorio.JuegosOlimpicos/LibreriaWeb/Views/Atleta/CreateAtleta.cshtml
@model LibreriaWeb.Models.Atleta.AtletaViewModel

@{
    ViewData["Title"] = "Create";
}

<h1>Crea un Atleta</h1>

<h4>AtletaViewModel</h4>
<hr />

<div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
    <ul class="navbar-nav flex-grow-1">
        <li class="nav-item">
            <a class="nav-link text-dark" asp-area="" asp-controller="Atleta" asp-action="Create">Crear</a>
        </li>
    </ul>
</div>

<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>

            <div class="form-group">
                <label asp-for="Nombre" class="control-label"></label>
                <input asp-for="Nombre" class="form-control" />
                <span asp-validation-for="Nombre" class="text-danger"></span>
            </div>

            <div class="form-group">
                <label asp-for="Apellido" class="control-label"></label>
                <input asp-for="Apellido" class="form-control" />
                <span asp-validation-for="Apellido" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Sexo" class="control-label"></label>
                <input asp-for="Sexo" class="form-control" />
                <span asp-validation-for="Sexo" class="text-danger"></span>
            </div>

            <div class="form-group">
                <label asp-for="Pais" class="control-label"></label>
                <input asp-for="Pais" class="form-control" />
                <span asp-validation-for="Pais" class="text-danger"></span>
            </div>

            <div class="form-group">
                <input type="submit" value="Crear" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Volver a la lista</a>
</div>

@section Scripts {
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
}